name: mineral_i18n
description: I18n allows you to translate your text content into multiple languages
version: 2.0.0

repository: https://github.com/mineral-dart/i18n
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

platforms:
  linux:
  macos:
  windows:

dependencies:
  mineral_ioc: ^2.0.0
  mineral: ^3.1.0
  path: ^1.8.2
  yaml: ^3.1.1
  mineral_contract: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
